name: Make Repo Public

on:
  schedule:
    - cron: '05 12 29 11 *' # Exécute le 29 novembre à 11h45 UTC

jobs:
  make-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make repository public
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }} \
            -d '{"private": false}'
