name: Make Repo Public
on:
  schedule:
    # Définissez l'heure à laquelle le dépôt deviendra public (UTC).
    - cron: '23 11 29 11 *' # Chaque jour à minuit du 1er au 24 décembre.

jobs:
  make-public:
    runs-on: ubuntu-latest
    steps:
    - name: Make the repository public
      run: |
        gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
        gh repo edit ${{ github.repository }} --visibility public
